################################################################################
# Title: Data Step for Hep B birth dose analysis
# Author: Daniel Vader
# Date: 1/11/2019
# Requires: NIS-Child 2017 public use data and data import file.
#           https://www.cdc.gov/vaccines/imz-managers/nis/datasets.html
################################################################################


################################################################################
# Load libraries and datasets
################################################################################
library(dplyr)

# Read in original dataset generated by NIS provided code and filter for 
# adequate provider data. 
#NIS2017 <- filter(NISPUF17, PDAT == 1)
#saveRDS(NIS2017, "NIS2017.rds")

# Read in previously saved dataset
NIS2017f <- readRDS("NIS2017.rds")


################################################################################
# Set up-to-date (UTD) variables for DTAP, Polio, Measles, Hep B, Varicella, PCV13, 
# Hib, the combined 3 series, the combined 5 series, and the combined 7 series
################################################################################

utd.age <- 18 # UTD age in months

# Function to set child to UTD if they have received the i-th dose of vaccine by
#   n months of age
utd.test <- function(vac.age, t.age = utd.age){
  ifelse(vac.age > t.age | is.na(vac.age), 0, 1)
}

# Create individual vaccine UTD variables
NIS2017f$utd.dt <- utd.test(NIS2017f$DTP4_AGE) # 4+ DT containing doses
NIS2017f$utd.pol <- utd.test(NIS2017f$POL3_AGE) # 3+ Polio containing doses
NIS2017f$utd.mmr <- utd.test(NIS2017f$MMR1_AGE) # 1+ Measles containing doses
NIS2017f$utd.hepb <- utd.test(NIS2017f$HEP3_AGE) # 3+ Hep B containing doses
NIS2017f$utd.var <- utd.test(NIS2017f$VRC1_AGE) # 1+ Varicella-containing doses
NIS2017f$utd.pcv <- utd.test(NIS2017f$PCV4_AGE) # 4+ doses PCV13-containing doses

# Hib UTD status depends on the manufacturer of doses 1 & 2. If both doses are
# made by Merck ("HM"), only 3 total doses are required. If one of the first two doses
# is not made by Merck or is made by an unknown manufacturer, 4 doses are required.
NIS2017f$utd.hib <- ifelse(NIS2017f$XHIBTY1 != "HM" | NIS2017f$XHIBTY2 != "HM" |
                               is.na(NIS2017f$XHIBTY1) | is.na(NIS2017f$XHIBTY2),
                             utd.test(NIS2017f$HIB4_AGE),
                             utd.test(NIS2017f$HIB3_AGE))

# Test categorization of Hib UTD
# NIS2017f$merck2 <- ifelse(NIS2017f$XHIBTY1 != "HM" | NIS2017f$XHIBTY2 != "HM" | 
#                            is.na(NIS2017f$XHIBTY1) | is.na(NIS2017f$XHIBTY2), 0, 1) 
# NIS2017f %>% {table(.$HIB3_AGE, .$utd.hib.n, .$merck2, useNA = "ifany")}
# NIS2017f %>% {table(.$HIB4_AGE, .$utd.hib.n, .$merck2, useNA = "ifany")}


## Create combined UTD variables
NIS2017f$utd.comb3 <- ifelse(NIS2017f$utd.dt + NIS2017f$utd.pol + NIS2017f$utd.mmr == 3, 1, 0)
NIS2017f$utd.comb5 <- ifelse(NIS2017f$utd.comb3 + NIS2017f$utd.hib + NIS2017f$utd.hepb == 3, 1, 0)
NIS2017f$utd.comb7 <- ifelse(NIS2017f$utd.comb5 + NIS2017f$utd.var + NIS2017f$utd.pcv == 3, 1, 0)

## Create combined UTD variables excluding hep B
NIS2017f$utd.comb5.nohep <- ifelse(NIS2017f$utd.comb3 + NIS2017f$utd.hib == 2, 1, 0)
NIS2017f$utd.comb7.nohep <- ifelse(NIS2017f$utd.comb5.nohep + NIS2017f$utd.var + NIS2017f$utd.pcv == 3, 1, 0)

# Create variable for birth dose of Hep B vaccine where:
#### a) 0 is zero doses of hep B OR provider did not indicate hep B birth dose 
#### b) 1 is provider indicated hep B birth dose.
NIS2017f$birthhep <- ifelse(NIS2017f$P_NUMHEP == 0 & is.na(NIS2017f$HEP_BRTH), 0, 
                           ifelse(NIS2017f$HEP_BRTH == 2, 0, 1))
NIS2017f$birthhep <- NIS2017f$U3D_HEP

################################################################################
# Subset data
################################################################################

# filter for variables of interest
NIS2017s <- select(NIS2017f, 
                   "SEQNUMC", # Child identifier
                   "PROVWT_D", # Weights for children with adequate provider data
                   "STRATUM", # Strata
                   "AGEGRP", # Age group of child
                   "CHILDNM", # Num of children <18 in household
                   "CWIC_01",
                   "CWIC_02", # Child currently receiving WIC benefits?
                   "EDUC1", # Education of mother
                   "FRSTBRN", # First born status of child
                   "INCPORAR_I", # Income-Poverty ratio (imputed)
                   "M_AGEGRP2", # Age group of mother (imputed)
                   "MARITAL2", # Marital status of mother (imputed)
                   "MOBIL_I", # Geographic mobility status
                   "RACEETHK", # Race/Ethnicity of child
                   "RENT_OWN", # Housing status
                   "SEX", # Sex of child
                   "ESTIAP17", # Estimation area of residence
                   "D6R", # Num of vaccination providers ident by respondent
                   "N_PRVR", # Num of responding providers
                   "PROV_FAC", # Provider facility types (imputed)
                   "REGISTRY", # Child's providers reported vacc to registry
                   "VFC_ORDER", # Vaccines ordered from state/local health dept?
                   "birthhep", # Hep B shot given at birth
                   "utd.hepb", # 3+ hep shots given by 36mo
                   "utd.var", # UTD varicella
                   "utd.hib", # UTD Hib strict def
                   "utd.mmr", # UTD measles containing vac
                   "utd.pcv", # UTD Pneumococcal vac (4+ doses)
                   "utd.pol", # UTD 3+ polio
                   "utd.dt", # UTD 4+ DT containing
                   "utd.comb3", # UTD on 4:3:1 series
                   "utd.comb5", # UTD on 4:3:1:3:3:1 series (strict Hib def)
                   "utd.comb7", # UTD on 4:3:1:3:3:1:4 series (strict Hib def)
                   "utd.comb5.nohep", # UTD on 4:3:1:3:3:1 series, hep b excluded
                   "utd.comb7.nohep", # UTD on 4:3:1:3:3:1:4 series, hep b excluded
                   "DHEPB1", # Age at first hep B shot (days)
                   "INS_BREAK_I", # Break in insurance 
                   "INS_STAT2_I" # Current insurance status
                   ) 


# 290 expected missing for provider-related data (No vaccines, no providers)
NIS2017final <- filter(NIS2017s, NIS2017s$N_PRVR !=0)

saveRDS(NIS2017final, "NIS2017final.rds")
