# This code was extracted/adapted from the NISPUF17.R file authored by the NIS.
# Initializes function to create factors for categorical variables in NIS-CHILD
# 2017. Lines pertaining to unused variables have been deleted or commented out.
# https://www.cdc.gov/vaccines/imz-managers/nis/datasets.html 

#library(Hmisc)

apply_nis_formats <- function(NISPUF17){

  ############################################################################
  # Step 1:   CREATE FORMATS                                                 #
  ############################################################################
  
  AGEGRPlevels=c(1,2,3)
  AGEGRPlabels=c("19 - 23 MONTHS", "24 - 29 MONTHS", "30 - 35 MONTHS")
  
  YNDKRFlevels=c(1,2,77,99)
  YNDKRFlabels=c("YES", "NO", "DON'T KNOW", "REFUSED")
  
  CHILDNMlevels=c(1,2,3,77,99)
  CHILDNMlabels=c("ONE", "TWO OR THREE", "FOUR OR MORE", "DON'T KNOW", "REFUSED")
  
  CWIClevels=c(1,2,3,77,99)
  CWIClabels=c("YES", "NO", "NEVER HEARD OF WIC", "DON'T KNOW", "REFUSED")
  
  EDUC1_levels=c(1,2,3,4,77,99)
  EDUC1_labels=c("< 12 YEARS", "12 YEARS", "> 12 YEARS, NON-COLLEGE GRAD", "COLLEGE GRAD", "DON'T KNOW", "REFUSED")
  
  MOBILlevels=c(1,2,77,99)
  MOBILlabels=c("MOVED FROM DIFFERENT STATE", "DID NOT MOVE FROM DIFFERENT STATE", "DON'T KNOW", "REFUSED")
  
  SEXlevels=c(1,2,77,99)
  SEXlabels=c("MALE", "FEMALE", "DON'T KNOW", "REFUSED")
  
  INCPOVlevels=c(1,2,3,4)
  INCPOVlabels=c("ABOVE POVERTY, > $75K", "ABOVE POVERTY, <= $75K", "BELOW POVERTY", "UNKNOWN")
  
  HASPDA2Flevels=c(1,2)
  HASPDA2Flabels=c("CHILD HAS ADEQUATE PROVIDER DATA OR ZERO VACCINATIONS", "CHILD DOES NOT HAVE ADEQUATE PROVIDER DATA")
  
  PROVIDlevels=c(1,2,3,4,5,6,7)
  PROVIDlabels=c("ALL PUBLIC FACILITIES", "ALL HOSPITAL FACILITIES", "ALL PRIVATE FACILITIES", "ALL MILITARY/OTHER FACILITIES", "MIXED", "TYPE OF PROVIDER UNKNOWN", "ALL WIC CLINIC PROVIDERS")
  
  REGISTRYlevels=c(1,2,3,4)
  REGISTRYlabels=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW")

  REGISTRYlevels_RC=c(1,2,3,4,99)
  REGISTRYlabels_RC=c("ALL PROVIDERS", "SOME BUT POSSIBLY OR DEFINITELY NOT ALL PROVIDERS", "NO PROVIDERS", "UNKNOWN/DON'T KNOW", "NON-VACCINATOR")
  
    
  TYPElevels=c("","01","02","03","04","05","07","08","1L","1M","1N","20","21","22","30","31","32","33","43","44","60","70","71","72","73","74","BC","D3","DH","DK","FL","FM","FN","FO","H2","HA","HB","HG","HI","HM","HS","HY","MA","MB","MM","MP","NC","OT","RB",
               "RG","RM","RO","TY","UN","VA","VM","VO","YF")
  TYPElabels=c("MISSING", "DT", "DTP", "DTP-UNKNOWN", "DTAP", "DTP-HIB", "DTAP-HIB", "DTAP-HEPB-IPV", "H1N1 FLU-UNKNOWN", "H1N1 FLU SPRAY", "H1N1 FLU INJECTED", "OPV", "IPV", "POLIO-UNKNOWN", "MMR", "MEASLES ONLY", "MEASLES-MUMPS", "MEASLES-RUBELLA",
               "HEPB-HIB", "HIB ONLY-UNKNOWN", "HEPB ONLY", "PCV CONJUGATE-UNKNOWN", "PCV POLYSACCHARIDE", "PCV-UNKNOWN", "PCV CONJUGATE-7", "PCV CONJUGATE-13", "BCG (TUBERCULOSIS)", "DTAP-IPV-HIB", "DTP-HEPB", "DON'T KNOW", "SEASONAL FLU-UNKNOWN", "SEASONAL FLU SPRAY",
               "SEASONAL FLU INJECTED", "FOUR-IN-ONE", "HIB (SANOFI OR GLAXOSMITHKLINE)", "HEPA", "HEPB-UNKNOWN", "HIB (GLAXOSMITHKLINE)", "HIB-UNKNOWN", "HIB (MERCK)", "HIB (SANOFI)", "HIB-MENCY", "MALARIA", "MUMPS-RUBELLA", "MCV-UNKNOWN", "MUMPS", "NEVER CODABLE",
               "OTHER", "RUBELLA", "ROTARIX (GSK)", "ROTATEQ (MERCK)", "ROTAVIRUS-UNKNOWN", "TYPHOID", "UNCODABLE", "VARICELLA-UNKNOWN", "MMR-VARICELLA", "VARICELLA-ONLY", "YELLOW FEVER")
  
  HEPBRTlevels=c(1,2)
  HEPBRTlabels=c("AT LEAST ONE PROVIDER CHECKED GIVEN AT BIRTH", "NO PROVIDERS CHECKED GIVEN AT BIRTH")
  
  HEPFLGlevels=c(1,2)
  HEPFLGlabels=c("HEPB BIRTH SHOT DATE IMPUTED FROM SHOTCARD", "HEPB BIRTH SHOT DATE IMPUTED FROM DISTRIBUTION OF BIRTH DOSE DATES")
  
  UTDlevels=c(0,1)
  UTDlabels=c("NOT UTD", "UTD")
  
  STATElevels=c(1,10,11,12,13,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,4,40,41,42,44,45,46,47,48,49,5,50,51,53,54,55,56,6,66,72,78,8,9)
  STATElabels=c("ALABAMA", "DELAWARE", "DISTRICT OF COLUMBIA", "FLORIDA", "GEORGIA", "HAWAII", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "ALASKA", "KANSAS", "KENTUCKY", "LOUISIANA", "MAINE", "MARYLAND", "MASSACHUSETTS", "MICHIGAN", "MINNESOTA", "MISSISSIPPI",
                "MISSOURI", "MONTANA", "NEBRASKA", "NEVADA", "NEW HAMPSHIRE", "NEW JERSEY", "NEW MEXICO", "NEW YORK", "NORTH CAROLINA", "NORTH DAKOTA", "OHIO", "ARIZONA", "OKLAHOMA", "OREGON", "PENNSYLVANIA", "RHODE ISLAND", "SOUTH CAROLINA", "SOUTH DAKOTA", "TENNESSEE",
                "TEXAS", "UTAH", "ARKANSAS", "VERMONT", "VIRGINIA", "WASHINGTON", "WEST VIRGINIA", "WISCONSIN", "WYOMING", "CALIFORNIA", "GUAM", "PUERTO RICO", "U.S. VIRGIN ISLANDS", "COLORADO", "CONNECTICUT")
  
  AGECPOXRlevels=c(1,2,3,4)
  AGECPOXRlabels=c("0 TO 6 MONTHS OLD", "7 TO 12 MONTHS OLD", "13 TO 18 MONTHS OLD", "19+ MONTHS OLD")
  
  C1Rlevels=c(1,2,3,4,5,6,7,8)
  C1Rlabels=c("1", "2", "3", "4", "5", "6", "7", "8+")
  
  RACEETHKlevels=c(1,2,3,4)
  RACEETHKlabels=c("HISPANIC", "NON-HISPANIC WHITE ONLY", "NON-HISPANIC BLACK ONLY", "NON-HISPANIC OTHER + MULTIPLE RACE")
  
  D6Rlevels=c(0,1,2,3)
  D6Rlabels=c("0", "1", "2", "3+")
  
  FRSTBRNlevels=c(1,2,77,99)
  FRSTBRNlabels=c("NO", "YES", "DON'T KNOW", "REFUSED")
  
  BFFORM08Flevels=c(888)
  BFFORM08Flabels=c("NEVER FED FORMULA")
  
  RENTOWNlevels=c(1,2,3,77,99)
  RENTOWNlabels=c("OWNED OR BEING BOUGHT", "RENTED", "OTHER ARRANGMENT", "DON'T KNOW", "REFUSED")
  
  MAR_PUF2_levels=c(1,2)
  MAR_PUF2_labels=c("MARRIED", "NEVER MARRIED/WIDOWED/DIVORCED/SEPARATED/DECEASED/LIVING WITH PARTNER")
  
  UTDPCVBlevels=c(1,2,3)
  UTDPCVBlabels=c("4+ PCV7 PLUS 1+ PCV13", "4+ PCV7, NO FOLLOWING PCV13, WITH TYPE OF ALL VACCINES (IF ANY) FOLLOWING THE 4 PCV7 KNOWN", "ALL OTHERS WITH ADEQUATE PROVIDER DATA")
  
  ESTGRANTlevels=c(1,10,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8)
  ESTGRANTlabels=c("CT", "NY-REST OF STATE", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN", "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME",
                   "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO", "MT", "ND", "SD", "UT", "WY", "AZ", "CA", "VT", "HI", "NV", "AK", "ID", "OR", "WA", "NJ")
  
  INS_BREAK_Ilevels=c(1,2,3,4)
  INS_BREAK_Ilabels=c("CURRENTLY INSURED BUT UNINSURED AT SOME POINT SINCE BIRTH", "CURRENTLY INSURED AND NEVER UNINSURED SINCE BIRTH", "CURRENTLY UNINSURED BUT INSURED AT SOME POINT SINCE BIRTH",
                      "CURRENTLY UNINSURED AND NEVER INSURED SINCE BIRTH")
  
  MAGEGRP2_levels=c(1,2,77,99)
  MAGEGRP2_labels=c("<= 29 YEARS", ">= 30 YEARS", "DON'T KNOW", "REFUSED")
  
  ESTIAP17Flevels=c(1,10,105,106,108,11,12,13,14,16,17,18,19,2,20,22,25,27,28,29,30,31,34,35,36,38,4,40,41,44,46,47,49,5,50,51,52,53,54,55,56,57,58,59,6,60,61,62,63,64,65,66,68,7,72,73,74,75,76,77,8,95)
  ESTIAP17Flabels=c("CT", "NY-REST OF STATE", "GUAM", "PUERTO RICO", "TX-TRAVIS COUNTY", "NY-CITY OF NEW YORK", "DC", "DE", "MD", "PA-REST OF STATE", "PA-PHILADELPHIA COUNTY", "VA", "WV", "MA", "AL", "FL", "GA", "KY", "MS", "NC", "SC", "TN",
                    "IL-REST OF STATE", "IL-CITY OF CHICAGO", "IN", "MI", "ME", "MN", "OH", "WI", "AR", "LA", "NM", "NH", "OK", "TX-REST OF STATE", "TX-DALLAS COUNTY", "TX-EL PASO COUNTY", "TX-CITY OF HOUSTON", "TX-BEXAR COUNTY", "IA", "KS", "MO", "NE", "RI", "CO", "MT",
                    "ND", "SD", "UT", "WY", "AZ", "CA", "VT", "HI", "NV", "AK", "ID", "OR", "WA", "NJ", "US VIRGIN ISLANDS")
  
  INS_STAT2_Ilevels=c(1,2,3,4)
  INS_STAT2_Ilabels=c("PRIVATE INSURANCE ONLY", "ANY MEDICAID", "OTHER INSURANCE", "UNINSURED")
  
  
  # ############################################################################
  # # Step 2:   ASSIGN VARIABLE LABELS                                         #
  # ############################################################################
  # 
  # label(NISPUF17$SEQNUMC) <- "UNIQUE CHILD IDENTIFIER"
  # 
  # label(NISPUF17$PROVWT_D) <- "FINAL DUAL-FRAME PROVIDER-PHASE WEIGHT (EXCLUDES TERRITORIES)"
  # 
  # label(NISPUF17$STRATUM) <- "STRATUM VARIABLE FOR DUAL-FRAME VARIANCE ESTIMATION"
  # label(NISPUF17$AGEGRP) <- "AGE CATEGORY OF CHILD (19-23, 24-29, 30-35 MO) (RECODE)"
  # 
  # label(NISPUF17$CHILDNM) <- "NUMBER OF CHILDREN LESS THAN 18 YEARS IN HH (RECODE)"
  # 
  # label(NISPUF17$CWIC_01) <- "CHILD EVER RECEIVED WIC BENEFITS?"
  # label(NISPUF17$CWIC_02) <- "CHILD CURRENTLY RECEIVING WIC BENEFITS?"
  # label(NISPUF17$EDUC1) <- "EDUCATION OF MOTHER CATEGORIES: IMPUTED (RECODE)"
  # label(NISPUF17$FRSTBRN) <- "FIRST BORN STATUS OF CHILD: IMPUTED"
  # 
  # label(NISPUF17$INCPORAR_I) <- "INCOME TO POVERTY RATIO: IMPUTED (RECODE)"
  # 
  # label(NISPUF17$M_AGEGRP2) <- "AGE OF MOTHER CATEGORIES: IMPUTED (RECODE)"
  # label(NISPUF17$MARITAL2) <- "MARITAL STATUS OF MOTHER: IMPUTED (RECODE)"
  # label(NISPUF17$MOBIL_I) <- "GEOGRAPHIC MOBILITY STATUS: STATE OF RESIDENCE OF CHILD AT BIRTH VERSUS CURRENT STATE: IMPUTED"
  # 
  # label(NISPUF17$RACEETHK) <- "RACE/ETHNICITY OF CHILD: IMPUTED (RECODE)"
  # label(NISPUF17$RENT_OWN) <- "IS HOME OWNED/BEING BOUGHT, RENTED, OR OCCUPIED BY SOME OTHER ARRANGEMENT?"
  # 
  # label(NISPUF17$ESTIAP17) <- "ESTIMATION AREA OF RESIDENCE"
  # label(NISPUF17$D6R) <- "NUMBER OF VACCINATION PROVIDERS IDENTIFIED BY RESPONDENT (RECODE)"
  # 
  # label(NISPUF17$N_PRVR) <- "NUMBER OF PROVIDERS RESPONDING WITH VACCINATION DATA FOR CHILD (RECODE)"
  # label(NISPUF17$PROV_FAC) <- "PROVIDER FACILITY TYPES: IMPUTED"
  # label(NISPUF17$REGISTRY) <- "CHILD'S PROVIDERS REPORTED CHILD'S VACCINATIONS TO IMMUNIZATION REGISTRY"
  # label(NISPUF17$VFC_ORDER) <- "DO CHILD'S PROVIDERS ORDER VACCINES FROM STATE/LOCAL HEALTH DEPT?"
  # label(NISPUF17$HEP_BRTH) <- "HEPATITIS B-CONTAINING SHOT GIVEN AT BIRTH FLAG"
  # 
  # label(NISPUF17$P_NUMHEP) <- "NUMBER OF HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE DETERMINED FROM PROVIDER INFO, EXCLUDING ANY VACCINATIONS AFTER THE HH INTERVIEW DATE."
  # label(NISPUF17$P_UTD431) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1 BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
  # label(NISPUF17$P_UTDHEP) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 3+ HEPATITIS B-CONTAINING SHOTS BY 36 MONTHS OF AGE, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
  # 
  # label(NISPUF17$P_UTD431H31_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INT
  # ERVIEW DATE."
  # label(NISPUF17$P_UTD431H313_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:3 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
  # INTERVIEW DATE."
  # label(NISPUF17$P_UTD431H314_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3:1:4 BY 36 MONTHS OF AGE (INCLUDES 1+ VARICELLA-CONTAINING AT AGE 12+ MTHS) USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD 
  # INTERVIEW DATE."
  # label(NISPUF17$P_UTD431H3_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
  # label(NISPUF17$P_UTD431H_ROUT_S) <- "UTD (UP-TO-DATE) FLAG FOR PROVIDER 4:3:1:3 BY 36 MONTHS OF AGE, USING THE ROUTINE, STRICT DEFINITION OF HIB UTD, EXCLUDING ANY VACCINATIONS AFTER THE HOUSEHOLD INTERVIEW DATE."
  # 
  # label(NISPUF17$INS_STAT2_I) <- "INSURANCE STATUS (PRIVATE ONLY/ANY MEDICAID/OTHER INSURANCE/UNINSURED): IMPUTED"
  # label(NISPUF17$INS_BREAK_I) <- "CONTINUITY OF INSURANCE COVERAGE SINCE BIRTH: IMPUTED"
  
  ############################################################################
  # Step 3:   ASSIGN FORMATS                                                 #
  #	  FORMATS ARE APPLICABLE ONLY TO CATEGORICAL VARIABLES	IN R             #
  ############################################################################
  
  NISPUF17$AGEGRP <- factor(NISPUF17$AGEGRP, levels=AGEGRPlevels, labels=AGEGRPlabels)
  NISPUF17$CHILDNM <- factor(NISPUF17$CHILDNM, levels=CHILDNMlevels, labels=CHILDNMlabels)
  NISPUF17$CWIC_02 <- factor(NISPUF17$CWIC_02, levels=YNDKRFlevels, labels=YNDKRFlabels)
  NISPUF17$CWIC_01 <- factor(NISPUF17$CWIC_01, levels=CWIClevels, labels=CWIClabels)
  NISPUF17$SEX <- factor(NISPUF17$SEX, levels=SEXlevels, labels=SEXlabels)
  
  NISPUF17$EDUC1 <- factor(NISPUF17$EDUC1, levels=EDUC1_levels, labels=EDUC1_labels)
  NISPUF17$FRSTBRN <- factor(NISPUF17$FRSTBRN, levels=FRSTBRNlevels, labels=FRSTBRNlabels)
  NISPUF17$M_AGEGRP2 <- factor(NISPUF17$M_AGEGRP2, levels=MAGEGRP2_levels, labels=MAGEGRP2_labels)
  NISPUF17$MARITAL2 <- factor(NISPUF17$MARITAL2, levels=MAR_PUF2_levels, labels=MAR_PUF2_labels)
  
  NISPUF17$MOBIL_I <- factor(NISPUF17$MOBIL_I, levels=MOBILlevels, labels=MOBILlabels)
  NISPUF17$RACEETHK <- factor(NISPUF17$RACEETHK, levels=RACEETHKlevels, labels=RACEETHKlabels)
  NISPUF17$RENT_OWN <- factor(NISPUF17$RENT_OWN, levels=RENTOWNlevels, labels=RENTOWNlabels)
  NISPUF17$ESTIAP17 <- factor(NISPUF17$ESTIAP17, levels=ESTIAP17Flevels, labels=ESTIAP17Flabels)
  
  NISPUF17$D6R <- factor(NISPUF17$D6R, levels=D6Rlevels, labels=D6Rlabels)
  NISPUF17$N_PRVR <- factor(NISPUF17$N_PRVR, levels=D6Rlevels, labels=D6Rlabels)
  NISPUF17$PROV_FAC <- factor(NISPUF17$PROV_FAC, levels=PROVIDlevels, labels=PROVIDlabels)
  NISPUF17$REGISTRY <- factor(NISPUF17$REGISTRY, levels=REGISTRYlevels, labels=REGISTRYlabels)
  NISPUF17$VFC_ORDER <- factor(NISPUF17$VFC_ORDER, levels=REGISTRYlevels, labels=REGISTRYlabels)
  
  # NISPUF17$HEP_BRTH <- factor(NISPUF17$HEP_BRTH, levels=HEPBRTlevels, labels=HEPBRTlabels)
  # NISPUF17$P_UTDHEP <- factor(NISPUF17$P_UTDHEP, levels=UTDlevels, labels=UTDlabels)
  
  # NISPUF17$P_UTD431 <- factor(NISPUF17$P_UTD431, levels=UTDlevels, labels=UTDlabels)
  # NISPUF17$P_UTD431H_ROUT_S <- factor(NISPUF17$P_UTD431H_ROUT_S, levels=UTDlevels, labels=UTDlabels)
  # NISPUF17$P_UTD431H3_ROUT_S <- factor(NISPUF17$P_UTD431H3_ROUT_S, levels=UTDlevels, labels=UTDlabels)
  # NISPUF17$P_UTD431H314_ROUT_S <- factor(NISPUF17$P_UTD431H314_ROUT_S, levels=UTDlevels, labels=UTDlabels)
  # NISPUF17$P_UTD431H313_ROUT_S <- factor(NISPUF17$P_UTD431H313_ROUT_S, levels=UTDlevels, labels=UTDlabels)
  # NISPUF17$P_UTD431H31_ROUT_S <- factor(NISPUF17$P_UTD431H31_ROUT_S, levels=UTDlevels, labels=UTDlabels)
  
  NISPUF17$INS_BREAK_I <- factor(NISPUF17$INS_BREAK_I, levels=INS_BREAK_Ilevels, labels=INS_BREAK_Ilabels)
  NISPUF17$INS_STAT2_I <- factor(NISPUF17$INS_STAT2_I, levels=INS_STAT2_Ilevels, labels=INS_STAT2_Ilabels)
  
  # Drop unused factor levels
  NISPUF17[] <- lapply(NISPUF17, function(x) if(is.factor(x)) factor(x) else x)
  
  return(NISPUF17)
}
